spring:
  application:
    name: annict-graphql
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: ${db.username}
    password: ${db.password}
  batch:
    jdbc:
      initialize-schema: never
annict:
  graphql: 
    endpoint: https://api.annict.com/graphql
    access-token: ${annict.access-token}
