spring:
  application:
    name: annict-graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testuser
  batch:
    jdbc:
      initialize-schema: never
graphql:
  annict: 
    endpoint: https://api.annict.com/graphql
